version: 2.1

orbs:
  node: circleci/node@5.2.0
jobs:
  build-test:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: '20.9.0'
workflows:
  build-app: 
    jobs:
      - build-test