version: 2.1

orbs:
  node: circleci/node@5.2.0
jobs:
  build-test:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - node/install:
          node-version: '20.9.0'
      - node/install-packages
      - run:
          command: npm run test
workflows:
  build-app: 
    jobs:
      - build-test